<?php

namespace SKCMS\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends EntityRepository
{
    
    public function find($id)
    {
        $qb = $this->createQueryBuilder('c');
        $qb ->where('c.id=:id')
            ->setParameter('id', $id)
            ->join('c.products', 'p')
            ->addSelect('p')
            ->join('p.productReference', 'pr')
            ->addSelect('pr')
                
                
            ;
        
        return $qb->getQuery()->getSingleResult();
    }
}
