<?php

namespace SKCMS\ShopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductUnityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationEmailRepository extends \SKCMS\CoreBundle\Repository\SKEntityRepository
{
}
